### ISSUE TITLE
laravel专用，为何不复用 Redis连接呢？

### ISSUE THREAD

**Issue by wanglelecc** [zhaocong6/laravel-lock#1]
用：
Illuminate\Support\Facades\Redis::connection();
替代：
$this->redis = new Client($config);

这样是否可行呢？主要是考虑到如果其它模块用到了 redis 缓存，这样的话同一个请求就需要建立两个 redis 连接

**Comment by zhaocong6** [comment]
可以

**Comment by zhaocong6** [comment]
复用连接, 必须是fpm模式

**Comment by wanglelecc** [comment]
好的，谢谢！
